[package]
name = "duanyan-ide"
version = "1.2.0"
edition = "2021"
authors = ["Zhujun"]
description = "DUANYAN IDE - The Duanyan Development Environment"

[lib]
name = "duanyan_ide_lib"
crate-type = ["staticlib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = { version = "4.2", optional = true }
espflash = { version = "4", features = ["serialport"] }
hardyscript = { path = "../../HardyScript" }
duanyan = { path = "../../DUANYAN", features = ["std"] }

[features]
default = ["bridge_serial"]
bridge_serial = ["serialport"]
