/* Auto-generated by HardyScript v1.5.0 — JS → C transpiler */
#include <stdint.h>
#include <stdio.h>
#include <stdint.h>

/* ===== HardyScript ESP32-S3 bare-metal HAL (WS2812 onboard RGB) ===== */
typedef unsigned int u32;
#define HARDY_REG(addr) (*(volatile u32 *)(addr))

#define HARDY_UART0_FIFO   HARDY_REG(0x60000000)
#define HARDY_UART0_STATUS HARDY_REG(0x6000001C)
#define HARDY_RTC_WDTCONFIG0  HARDY_REG(0x60008098)
#define HARDY_RTC_WDTFEED     HARDY_REG(0x600080AC)
#define HARDY_RTC_WDTWPROTECT HARDY_REG(0x600080B0)
#define HARDY_RTC_SWD_CONF    HARDY_REG(0x600080B4)
#define HARDY_RTC_SWD_WPROT   HARDY_REG(0x600080B8)
#define HARDY_TIMG0_T0CONFIG  HARDY_REG(0x6001F000)
#define HARDY_TIMG0_T0LO      HARDY_REG(0x6001F004)
#define HARDY_TIMG0_T0UPDATE  HARDY_REG(0x6001F00C)
#define HARDY_TIMG0_WDTCONFIG0  HARDY_REG(0x6001F048)
#define HARDY_TIMG0_WDTWPROTECT HARDY_REG(0x6001F064)
#define HARDY_TIMG0_INT_CLR     HARDY_REG(0x6001F07C)
#define HARDY_GPIO_BASE  0x60004000UL
#define HARDY_IOMUX_BASE 0x60009000UL

/* RMT 外设 (硬件波形发生器, 时序由 80MHz 时钟树保证, 与 CPU 频率无关) */
#define HARDY_PERIP_CLK_EN0  HARDY_REG(0x600C0018)
#define HARDY_RMT_BASE       0x60016000UL
#define HARDY_RMT_RAM_CH0    0x60016800UL
#define HARDY_RMT_CH0CONF0   HARDY_REG(HARDY_RMT_BASE + 0x20)
#define HARDY_RMT_INT_ST     HARDY_REG(HARDY_RMT_BASE + 0x74)
#define HARDY_RMT_INT_ENA    HARDY_REG(HARDY_RMT_BASE + 0x78)
#define HARDY_RMT_INT_CLR    HARDY_REG(HARDY_RMT_BASE + 0x7C)
#define HARDY_RMT_SYS_CONF   HARDY_REG(HARDY_RMT_BASE + 0xC0)
/* WS2812 时序 @ RMT sclk 实测 ~10MHz (ROM 无 PLL, 时钟树约标称 1/8):
 * T0H=0.4us T0L=0.8us T1H=0.8us T1L=0.4us, 对称居中, 解码裕量充足 */
#define HARDY_WS_T0H 4u
#define HARDY_WS_T0L 8u
#define HARDY_WS_T1H 8u
#define HARDY_WS_T1L 4u

static u32 _hardy_ticks_per_us = 10;

static void hardy_uart_putc(char c) {
    while (((HARDY_UART0_STATUS >> 16) & 0x3FF) >= 127) { }
    HARDY_UART0_FIFO = (u32)c;
}
static void hardy_uart_puts(const char *s) { while (*s) hardy_uart_putc(*s++); }
static void hardy_uart_num(u32 v) {
    char tmp[10]; int t = 0;
    do { tmp[t++] = (char)('0' + (v % 10)); v /= 10; } while (v > 0);
    while (t > 0) hardy_uart_putc(tmp[--t]);
}
static u32 hardy_timer_now(void) { HARDY_TIMG0_T0UPDATE = 1; return HARDY_TIMG0_T0LO; }
static void hardy_wait_ticks(u32 start, u32 ticks) {
    u32 cap = (ticks + 10) * 100 + 100000;
    while ((hardy_timer_now() - start) < ticks && cap--) { }
}
static void hardy_delay_us(u32 us) { hardy_wait_ticks(hardy_timer_now(), us * _hardy_ticks_per_us); }
static void hardy_delay_ms(u32 ms) { hardy_wait_ticks(hardy_timer_now(), ms * 1000 * _hardy_ticks_per_us); }
/* 开机自校准: 用 UART 115200 绝对基准实测 ticks/us */
static void hardy_calibrate(void) {
    u32 t0 = hardy_timer_now();
    for (int i = 0; i < 10; i++) hardy_uart_putc('~');
    while (((HARDY_UART0_STATUS >> 16) & 0x3FF) != 0) { }
    u32 ticks = hardy_timer_now() - t0;
    _hardy_ticks_per_us = ticks / 955;
    if (_hardy_ticks_per_us == 0) _hardy_ticks_per_us = 10;
}
static void hardy_pin_setup(u32 pin) {
    HARDY_REG(HARDY_IOMUX_BASE + pin * 4) = (1u << 12) | (3u << 10);
    HARDY_REG(HARDY_GPIO_BASE + 0x554 + pin * 4) = pin;
    if (pin >= 32) HARDY_REG(HARDY_GPIO_BASE + 0x30) = 1u << (pin - 32);
    else HARDY_REG(HARDY_GPIO_BASE + 0x24) = 1u << pin;
}
static void hardy_pin_hi(u32 pin) {
    if (pin >= 32) HARDY_REG(HARDY_GPIO_BASE + 0x14) = 1u << (pin - 32);
    else HARDY_REG(HARDY_GPIO_BASE + 0x08) = 1u << pin;
}
static void hardy_pin_lo(u32 pin) {
    if (pin >= 32) HARDY_REG(HARDY_GPIO_BASE + 0x18) = 1u << (pin - 32);
    else HARDY_REG(HARDY_GPIO_BASE + 0x0C) = 1u << pin;
}
/* RMT 初始化: 80MHz sclk, 通道0 单发模式, 输出路由到 GPIO48 (信号81) */
static void hardy_rmt_init(void) {
    HARDY_PERIP_CLK_EN0 |= (1u << 9);             /* RMT 时钟使能 */
    HARDY_RMT_SYS_CONF = (1u << 0) | (1u << 1) | (1u << 3)
                       | (1u << 4) | (1u << 24) | (1u << 26) | (1u << 31);
    HARDY_RMT_CH0CONF0 = (1u << 8) | (1u << 16) | (1u << 6); /* div=1, 1块RAM, idle低 */
    HARDY_RMT_CH0CONF0 |= (1u << 24);             /* CONF_UPDATE */
    HARDY_RMT_INT_ENA |= 1u;                      /* TX_END_CH0 状态可见 */
    /* 数据脚 GPIO48 交给 RMT: IO_MUX 设 GPIO 功能, FUNC_OUT_SEL = 81 */
    HARDY_REG(HARDY_IOMUX_BASE + 48 * 4) = (1u << 12) | (3u << 10);
    HARDY_REG(HARDY_GPIO_BASE + 0x554 + 48 * 4) = 81;
}
/* WS2812: 经 RMT 硬件发送 24bit GRB (MSB first), 帧含 50us 锁存间隙。
 * 每帧连发两遍: 偶发误码在 300us 内自修复, 人眼不可见, 彻底无闪烁 */
static void hardy_ws2812_send(u32 grb) {
    volatile u32 *ram = (volatile u32 *)HARDY_RMT_RAM_CH0;
    const u32 BASE_CONF = (1u << 8) | (1u << 16) | (1u << 6);
    for (int rep = 0; rep < 2; rep++) {
        for (int i = 0; i < 24; i++) {
            u32 hi = HARDY_WS_T0H, lo = HARDY_WS_T0L;
            if ((grb >> (23 - i)) & 1) { hi = HARDY_WS_T1H; lo = HARDY_WS_T1L; }
            ram[i] = hi | (1u << 15) | (lo << 16);
        }
        ram[24] = 500;   /* 50us 低电平 = WS2812 锁存间隙 */
        ram[25] = 0;     /* 结束标记 */
        HARDY_RMT_INT_CLR = 1;
        HARDY_RMT_CH0CONF0 = BASE_CONF | (1u << 1) | (1u << 2);  /* 复位读指针 */
        HARDY_RMT_CH0CONF0 = BASE_CONF;
        HARDY_RMT_CH0CONF0 = BASE_CONF | (1u << 24);  /* CONF_UPDATE */
        HARDY_RMT_CH0CONF0 = BASE_CONF | (1u << 0);   /* TX_START */
        /* 固定等待发完 (帧含锁存间隙约 80us, 等 120us 留足裕量)。
         * 不用 INT_ST 轮询: 实测它会提前退出, 提前重写 RAM 撕裂帧尾
         * 造成闪烁突发 (led_rmt.c 实测教训) */
        hardy_delay_us(120);
    }
}
static void hardy_rgb_set(int r, int g, int b) {
    if (r < 0) r = 0; if (r > 255) r = 255;
    if (g < 0) g = 0; if (g > 255) g = 255;
    if (b < 0) b = 0; if (b > 255) b = 255;
    hardy_ws2812_send(((u32)g << 16) | ((u32)r << 8) | (u32)b);
}
/* HSV 色轮 (亮度 1/4, 清晰可见且不眩眼) */
static void hardy_rgb_hue(int pos) {
    int r, g, b;
    pos = 255 - (pos & 255);
    if (pos < 85) { r = 255 - pos * 3; g = 0; b = pos * 3; }
    else if (pos < 170) { pos -= 85; r = 0; g = pos * 3; b = 255 - pos * 3; }
    else { pos -= 170; r = pos * 3; g = 255 - pos * 3; b = 0; }
    hardy_ws2812_send(((u32)(g >> 2) << 16) | ((u32)(r >> 2) << 8) | (u32)(b >> 2));
}
static void hardy_boot_init(void) {
    /* 关三只看门狗 */
    HARDY_RTC_WDTWPROTECT = 0x50D83AA1;
    HARDY_RTC_WDTFEED = 1;
    HARDY_RTC_WDTCONFIG0 = 0;
    HARDY_RTC_WDTWPROTECT = 0;
    HARDY_RTC_SWD_WPROT = 0x8F1D312A;
    HARDY_RTC_SWD_CONF = (1u << 30);
    HARDY_RTC_SWD_WPROT = 0;
    HARDY_TIMG0_WDTWPROTECT = 0x50D83AA1;
    HARDY_TIMG0_WDTCONFIG0 = 0;
    HARDY_TIMG0_INT_CLR = 0xFFFFFFFF;
    HARDY_TIMG0_WDTWPROTECT = 0;
    /* TIMG0 Timer0: APB 源, 分频=1, 使能 */
    HARDY_TIMG0_T0CONFIG = (1u << 13) | (1u << 30) | (1u << 31);
    hardy_calibrate();
    /* WS2812 供电使能 GPIO47 (不使能则灯不亮) */
    hardy_pin_setup(47);
    hardy_pin_hi(47);
    hardy_delay_ms(10);
    /* 数据脚 GPIO48 由 RMT 外设驱动 (软件模拟在低 CPU 频率下波形畸变) */
    hardy_rmt_init();
    hardy_uart_puts("[DUANYAN-OK] hardyscript bare boot (RMT)\r\n");
}

void _start(void) __attribute__((section(".entry"), used));
void _start(void)
{
    hardy_boot_init();
    int32_t hue = 0;
    int32_t n = 0;
    hardy_uart_puts("pace start\r\n");
    while (1) {
        hardy_rgb_hue(hue);
        hue = (hue + 1);
        if ((hue >= 256)) {
            hue = 0;
        }
        n = (n + 1);
        if ((n >= 83)) {
            n = 0;
            hardy_uart_puts("tick\r\n");
        }
        hardy_delay_ms(12);
    }
    for (;;) { }
}
